alarm[5]=300;
if (angry==0){
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=180;
tempid.speed=16;
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=203;
tempid.speed=16;
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=225;
tempid.speed=16;
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=248;
tempid.speed=16;
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=0;
tempid.speed=16;
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=-23;
tempid.speed=16;
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=-45;
tempid.speed=16;
tempid=instance_create(x+6,y+8,obj_visionchecke)
tempid.direction=-68;
tempid.speed=16;
}
angry=1;