obj_iji.startmusics=0;
obj_iji.takingpain=1;
obj_iji.recovering=0;
obj_iji.goaroundtrigger=1;

//Weapon combination messages
if (global.textid=="weapstation9"){
text[0]="BUSTER GUN                                                       Select this weapon by pressing the 1 key twice. A hybrid of the Shotgun and Machinegun, this weapon uses Machinegun ammunition.";
text[1]="This Nanoweapon behaves like a Shotgun, but fires more than thrice as fast, and uses lots of Machinegun bullets in the process. Perfect for taking out single large enemies.";
text[2]="Another way to select the Buster gun is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the Shotgun is selected, then pressing "+chr(global.specialkey)+".";
pages=3;}
if (global.textid=="weapstation10"){
text[0]="SPLINTERGUN                                                      Select this weapon by pressing the 2 key twice. A hybrid of the Machinegun and Shocksplinter, this weapon uses Machinegun ammunition.";
text[1]="This Nanoweapon fires `splinters`, which are the smaller shards generated by a Shocksplinter explosion, at the speed of a machinegun. It is effective both against large single enemies, and groups of smaller ones.";
text[2]="Another way to select the Splintergun gun is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the Machinegun is selected, then pressing "+chr(global.specialkey)+".";
pages=3;}
if (global.textid=="weapstation11"){
text[0]="SPREAD ROCKETS                                                   Select this weapon by pressing the 3 key twice. A hybrid of the Shotgun and Rocket launcher, this weapon uses Launcher ammunition.$";
text[1]="This Nanoweapon fires three rockets at once, and has a higher damage per second ratio than the Rocket launcher. Each shot uses 3 Launcher ammo, and it is primarily designed for taking out single large enemies.";
text[2]="Another way to select the Spread rockets is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the Rocket launcher is selected, then pressing "+chr(global.specialkey)+".";
pages=3;}
if (global.textid=="weapstation12"){
text[0]="NUKE                                                             Select this weapon by pressing the 4 key twice. A hybrid of the Rocket launcher and MPFB Devastator, this weapon uses MPFB ammunition.";
text[1]="This Nanoweapon deals immediate damage to all enemies in the vicinity, at the cost of 3 MPFB cells. Firing it knocks you flying, but doesn't hurt you. Ammunition efficiency is highly dependent on the situation this weapon is fired in.";
text[2]="Another way to select the Nuke is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the MPFB Devastator is selected, then pressing "+chr(global.specialkey)+".";
pages=3;}
if (global.textid=="weapstation13"){
text[0]="RESONANCE REFLECTOR                                              Select this weapon by pressing the 5 or "+chr(global.weap5key)+" key twice. A hybrid of the Shotgun and Resonance detonator, this weapon uses no ammunition.";
text[1]="This devious Nanoweapon cannot deal any direct damage, but is able to reflect mass-based projectiles, such as rockets, MPFB and shocksplinter. However, it cannot reflect instant-hit weapons or the Pulse cannon weapon types.";
if (global.rrkills)
    text[2]="Note: reflected projectiles DO award you kills when striking enemies.";
else
    text[2]="Note: reflected projectiles do NOT award you kills when striking enemies.";
text[3]="Another way to select the Resonance reflector is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the Resonance detonator is selected, then pressing "+chr(global.specialkey)+".";
pages=4;}
if (global.textid=="weapstation14"){
text[0]="HYPER PULSE                                                      Select this weapon by pressing the 6 or "+chr(global.weap6key)+" key twice. A hybrid of the Resonance detonator and Pulse cannon, this weapon uses Pulse cannon ammunition.";
text[1]="If an enemy has less than 33% of his armor left when hit by a Hyper pulse projectile, he will be knocked down, but only if your Strength level is high enough to let you kick the enemy down normally. Hyper pulse can also destroy Shield doors.";
text[2]="Another way to select the Hyper pulse is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the Pulse cannon is selected, then pressing "+chr(global.specialkey)+".";
pages=3;}
if (global.textid=="weapstation15"){
text[0]="PLASMA CANNON                                                    Select this weapon by pressing the 7 or "+chr(global.weap7key)+" key twice. A hybrid of the Pulse cannon and Shocksplinter, this weapon uses Shock ammunition.";
text[1]="This Nanoweapon fires an instant-hit plasma bolt, at the cost of 2 Shock cells. Only the very middle of the beam is dangerous; the surrounding light display is harmless. The beam causes a splinter explosion when it hits a solid wall.";
text[2]="Another way to select the Plasma cannon is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the Shocksplinter is selected, then pressing "+chr(global.specialkey)+".";
pages=3;}
if (global.textid=="weapstation16"){
text[0]="VELOCITHOR V2-10                                                 Select this weapon by pressing the 8 or "+chr(global.weap8key)+" key twice. A hybrid of the MPFB Devastator and Cyclic Fusion Ignition system, this weapon uses CFIS ammunition.";
text[1]="An upgraded Cyclic Fusion Ignition System, this Nanoweapon deals damage at a faster rate but has a slightly lower damage per ammunition rate. Its unstoppable power cuts straight through solid walls and enemies alike.";
text[2]="Another way to select the Velocithor V2-10 is to press "+chr(global.prevkey)+" or "+chr(global.nextkey)+" until the Cyclic Fusion Ignition System is selected, then pressing "+chr(global.specialkey)+".";
pages=3;}

//Special traits
if (global.textid=="specialtrait1"){
text[0]="As a result of upgrading your Health stat to level 10,           you have gained the Special trait SUPPRESSION.                   Special traits are permanent, and are earned for every stat that reaches level 10. Continue reading for more info on this trait.";
text[1]="With SUPPRESSION, your personal Nanofield gains extreme          resistance to Nano-based attacks. Whenever an attack deals more  than 1 hit point worth of damage in a single hit, the damage you receive will be reduced by 1 hit point.";
pages=2;
global.erasetop=0;
global.ignorestation=120;
global.topmessage="SPECIAL TRAIT INFO ADDED TO PAUSE MENU";}
if (global.textid=="specialtrait2"){
text[0]="As a result of upgrading your Attack stat to level 10,           you have gained the Special trait IMPROVED AUTOLOADING.          Special traits are permanent, and are earned for every stat that reaches level 10. Continue reading for more info on this trait.";
text[1]="With IMPROVED AUTOLOADING, the subroutine programming of your    Nanogun is enhanced, lowering the reload time of all             non-rapidfire weapons by 20%. This does not affect the time it   takes to switch Nanoweapons.";
pages=2;
global.erasetop=0;
global.ignorestation=120;
global.topmessage="SPECIAL TRAIT INFO ADDED TO PAUSE MENU";}
if (global.textid=="specialtrait3"){
text[0]="As a result of upgrading your Assimilate stat to level 10,       you have gained the Special trait ADVANCED RECOVERY.             Special traits are permanent, and are earned for every stat that reaches level 10. Continue reading for more info on this trait.";
text[1]="With ADVANCED RECOVERY, assimilating a red Nanofield will recover one additional Hit Point, and green Nanofields will recover one Hit Point instead of none. Additionally, your ammo capacity has been increased to 99.";
pages=2;
global.erasetop=0;
global.ignorestation=120;
global.topmessage="SPECIAL TRAIT INFO ADDED TO PAUSE MENU";}
if (global.textid=="specialtrait4"){
text[0]="As a result of upgrading your Strength stat to level 10,         you have gained the Special trait CYBERNETIC ENDURANCE.          Special traits are permanent, and are earned for every stat that reaches level 10. Continue reading for more info on this trait.";
text[1]="With CYBERNETIC ENDURANCE, the temporary invulnerability time    after being damaged is increased by 50%. You are no longer       knocked to the ground by the MPFB Devastator's recoil.";
pages=2;
global.erasetop=0;
global.ignorestation=120;
global.topmessage="SPECIAL TRAIT INFO ADDED TO PAUSE MENU";}
if (global.textid=="specialtrait5"){
text[0]="As a result of upgrading your Crack stat to level 10,            you have gained the Special trait ELECTRONIC MASTERY.            Special traits are permanent, and are earned for every stat that reaches level 10. Continue reading for more info on this trait.";
text[1]="With ELECTRONIC MASTERY, whenever you fail to crack something,   no adverse effects occur (enemies don't notice you, security     crates don't break/explode on higher difficulty levels etc),     blue nodes no longer flicker, and cracking time is increased.";
pages=2;
global.erasetop=0;
global.ignorestation=120;
global.topmessage="SPECIAL TRAIT INFO ADDED TO PAUSE MENU";}
if (global.textid=="specialtrait6"){
text[0]="As a result of upgrading your Tasen stat to level 10,            you have gained the Special trait VENGEANCE.                     Special traits are permanent, and are earned for every stat that reaches level 10. Continue reading for more info on this trait.";
text[1]="With VENGEANCE, you get +1 to all Tasen ammunition you pick up.";
pages=2;
global.erasetop=0;
global.ignorestation=120;
global.topmessage="SPECIAL TRAIT INFO ADDED TO PAUSE MENU";}
if (global.textid=="specialtrait7"){
text[0]="As a result of upgrading your Komato stat to level 10,           you have gained the Special trait GLORY.                         Special traits are permanent, and are earned for every stat that reaches level 10. Continue reading for more info on this trait.";
text[1]="With GLORY, you get +1 to all Komato ammunition you pick up.";
pages=2;
global.erasetop=0;
global.ignorestation=120;
global.topmessage="SPECIAL TRAIT INFO ADDED TO PAUSE MENU";}