repeat(5){
sound_stop(snd_iji_jump);
sound_stop(snd_iji_jump2);
sound_stop(snd_iji_kick);
sound_stop(snd_iji_kick2);
sound_stop(snd_iji_pain1);
sound_stop(snd_iji_pain2);
sound_stop(snd_iji_pain3);
sound_stop(snd_iji_bigpain1);
sound_stop(snd_iji_bigpain2);
sound_stop(snd_iji_death);
sound_stop(snd_iji_damnit);
sound_stop(snd_iji_cry1);
sound_stop(snd_iji_cry2);
sound_stop(snd_iji_berserk1);
sound_stop(snd_iji_berserk2);
sound_stop(snd_iji_berserk3);
sound_stop(snd_iji_ougi1);
sound_stop(snd_iji_ougi2);
sound_stop(snd_iji_breathe);
}