repeat(5){
sound_stop(snd_kro_pain1);
sound_stop(snd_kro_pain2);
sound_stop(snd_kro_death);
sound_stop(snd_kro_ambient1);
sound_stop(snd_kro_ambient2);
sound_stop(snd_kro_ambient3);
sound_stop(snd_kro_win);
sound_stop(snd_kro_emote2);
}