execute_key = argument0;

scr_executekey("escape", vk_escape);
scr_executekey("enter", vk_enter);
scr_executekey("u", vk_up);
scr_executekey("d", vk_down);
scr_executekey("l", vk_left);
scr_executekey("r", vk_right);
scr_executekey("z", ord('Z'));
scr_executekey("x", ord('X'));
scr_executekey("c", ord('C'));
scr_executekey("s", ord('S'));
scr_executekey("one", ord('1'));
scr_executekey("two", ord('2'));
scr_executekey("three", ord('3'));
scr_executekey("four", ord('4'));
scr_executekey("five", ord('5'));
scr_executekey("six", ord('6'));
scr_executekey("seven", ord('7'));
scr_executekey("eight", ord('8'));
scr_executekey("nine", ord('9'));
