execute_key = argument0;

scr_executekey("escape", vk_escape);
scr_executekey("enter", vk_enter);
scr_executekey("U", vk_up);
scr_executekey("D", vk_down);
scr_executekey("L", vk_left);
scr_executekey("R", vk_right);
scr_executekey("Z", ord('Z'));
scr_executekey("X", ord('X'));
scr_executekey("C", ord('C'));
scr_executekey("S", ord('S'));
scr_executekey("one", ord('1'));
scr_executekey("two", ord('2'));
scr_executekey("three", ord('3'));
scr_executekey("four", ord('4'));
scr_executekey("five", ord('5'));
scr_executekey("six", ord('6'));
scr_executekey("seven", ord('7'));
scr_executekey("eight", ord('8'));
scr_executekey("nine", ord('9'));
