with (obj_iji) crackmark=0;
with (obj_cdoor) crackmark=0;
with (obj_turret) crackmark=0;
with (obj_tasenscout) crackmark=0;
with (obj_tasensoldier) crackmark=0;
with (obj_tasencommander) crackmark=0;
with (obj_tasenelite) crackmark=0;
with (obj_tasenshredder) crackmark=0;
with (obj_komatotrooper) crackmark=0;
with (obj_komatoberserker) crackmark=0;
with (obj_komatoassassin) crackmark=0;
with (obj_komatobeast) crackmark=0;
with (obj_komatoannihilator) crackmark=0;
with (obj_crackbox) crackmark=0;
with (obj_weapstation) crackmark=0;
with (obj_terminal) crackmark=0;
with (obj_acmachine) crackmark=0;
with (obj_iosa2) crackmark=0;
with (obj_cracktext) instance_destroy();
with (obj_frame) instance_destroy();
with (obj_crackbar) instance_destroy();
with (obj_noderow) instance_destroy();
with (obj_nodecol) instance_destroy();
with (obj_younode) instance_destroy();
with (obj_goalnode) instance_destroy();
with (obj_icenode) instance_destroy();
with (obj_binary) instance_destroy();
with (obj_colnumber) instance_destroy();
obj_iji.niacrack=1;
obj_iji.alarm[5]=6;
global.cracking=0;
global.cracktime=1;
obj_shakescreen.alarm[1]=3;